### ISSUE TITLE
Errors after Bundle Exec

### ISSUE THREAD

**Issue by samirpatelindianic** [istiaqiut/xrp-e#1]
Samir-Patel:peatio Samar$ bundle exec rake yarn:install
yarn install v1.3.2
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 📃  Building fresh packages...
✨  Done in 1.01s.
Samir-Patel:peatio Samar$ brew install phantomjs
Updating Homebrew...
==> Auto-updated Homebrew!
Updated 1 tap (homebrew/core).
==> Updated Formulae
mpv

Warning: phantomjs 2.1.1 is already installed
Samir-Patel:peatio Samar$ brew install imagemagick
Updating Homebrew...
Warning: imagemagick 7.0.7-22 is already installed
Samir-Patel:peatio Samar$ bin/init_config
Copying lib/generators/config/templates/application.yml.erb -> config/application.yml
Copying lib/generators/config/templates/markets.yml.erb -> config/markets.yml
Copying lib/generators/config/templates/banks.yml.erb -> config/banks.yml
Copying lib/generators/config/templates/currencies.yml.erb -> config/currencies.yml
Samir-Patel:peatio Samar$ open /Applications/Bitcoin-Qt.app
Samir-Patel:peatio Samar$ bundle exec rake db:setup
rake aborted!
Psych::SyntaxError: (<unknown>): could not find expected ':' while scanning a simple key at line 8 column 3
/Users/Samar/peatio/config/application.rb:10:in `<module:Peatio>'
/Users/Samar/peatio/config/application.rb:9:in `<top (required)>'
/Users/Samar/peatio/Rakefile:5:in `require'
/Users/Samar/peatio/Rakefile:5:in `<top (required)>'
/Users/Samar/.rbenv/versions/2.5.0/bin/bundle:23:in `load'
/Users/Samar/.rbenv/versions/2.5.0/bin/bundle:23:in `<main>'
(See full trace by running task with --trace)
Samir-Patel:peatio Samar$ bundle exec rake solvency:liability_proof
rake aborted!
Psych::SyntaxError: (<unknown>): could not find expected ':' while scanning a simple key at line 8 column 3
/Users/Samar/peatio/config/application.rb:10:in `<module:Peatio>'
/Users/Samar/peatio/config/application.rb:9:in `<top (required)>'
/Users/Samar/peatio/Rakefile:5:in `require'
/Users/Samar/peatio/Rakefile:5:in `<top (required)>'
/Users/Samar/.rbenv/versions/2.5.0/bin/bundle:23:in `load'
/Users/Samar/.rbenv/versions/2.5.0/bin/bundle:23:in `<main>'
(See full trace by running task with --trace)
Samir-Patel:peatio Samar$ god -c lib/daemons/daemons.god
0000000   R   A   I   L   S   _   E   N   V           =       E   N   V
0000020   .   f   e   t   c   h   (   '   R   A   I   L   S   _   E   N
0000040   V   '   ,       '   d   e   v   e   l   o   p   m   e   n   t
0000060   '   )  \n   R   A   I   L   S   _   R   O   O   T       =    
0000100   F   i   l   e   .   e   x   p   a   n   d   _   p   a   t   h
0000120   (   '   .   .   /   .   .   /   .   .   '   ,       _   _   F
0000140   I   L   E   _   _   )  \n  \n   #       C   r   e   a   t   e
0000160       n   o   n   -   d   e   f   a   u   l   t       l   o   g
0000200   /   d   a   e   m   o   n   s       d   i   r   e   c   t   o
0000220   r   y   .  \n   r   e   q   u   i   r   e       '   f   i   l
0000240   e   u   t   i   l   s   '  \n   F   i   l   e   U   t   i   l
0000260   s   .   m   k   d   i   r   _   p       "   #   {   R   A   I
0000300   L   S   _   R   O   O   T   }   /   l   o   g   /   d   a   e
0000320   m   o   n   s   "  \n  \n   d   e   f       d   a   e   m   o
0000340   n   (   n   a   m   e   ,       o   p   t   i   o   n   s    
0000360   =       {   }   )  \n           G   o   d   .   w   a   t   c
0000400   h       d   o       |   w   |  \n                   c   o   m
0000420   m   a   n   d                                   =       "   b
0000440   u   n   d   l   e       e   x   e   c       r   u   b   y    
0000460   l   i   b   /   d   a   e   m   o   n   s   /   #   {   o   p
0000500   t   i   o   n   s   .   f   e   t   c   h   (   :   s   c   r
0000520   i   p   t   )   }   "  \n                   c   o   m   m   a
0000540   n   d                               +   =       '       '    
0000560   +       o   p   t   i   o   n   s   [   :   a   r   g   u   m
0000600   e   n   t   s   ]   .   j   o   i   n   (   '       '   )    
0000620   i   f       o   p   t   i   o   n   s   .   k   e   y   ?   (
0000640   :   a   r   g   u   m   e   n   t   s   )  \n                
0000660   f   i   l   e   s   a   f   e   _   n   a   m   e           =
0000700       n   a   m   e   .   g   s   u   b   (   /   \   W   /   ,
0000720       '   _   '   )  \n  \n                   w   .   n   a   m
0000740   e           =       n   a   m   e  \n                   w   .
0000760   s   t   a   r   t       =       c   o   m   m   a   n   d  \n
0001000                   w   .   l   o   g               =       "   #
0001020   {   R   A   I   L   S   _   R   O   O   T   }   /   l   o   g
0001040   /   d   a   e   m   o   n   s   /   #   {   f   i   l   e   s
0001060   a   f   e   _   n   a   m   e   }   .   l   o   g   "  \n    
0001100               w   .   d   i   r               =       R   A   I
0001120   L   S   _   R   O   O   T  \n                   w   .   e   n
0001140   v               =       {       '   R   A   I   L   S   _   E
0001160   N   V   '       =   >       R   A   I   L   S   _   E   N   V
0001200   ,       '   R   A   I   L   S   _   R   O   O   T   '       =
0001220   >       R   A   I   L   S   _   R   O   O   T       }  \n  \n
0001240                   #       P   e   a   t   i   o       h   a   s
0001260       l   o   t       o   f       d   e   p   e   n   d   e   n
0001300   c   i   e   s       w   h   i   c   h       t   a   k   e    
0001320   s   o   m   e       t   i   m   e       t   o       l   o   a
0001340   d       e   v   e   r       o   n       f   a   s   t       d
0001360   i   s   k   s   .  \n                   #       G   o   d   ,
0001400       b   y       d   e   f   a   u   l   t   ,       d   o   e
0001420   s   n   '   t       w   a   i   t       b   e   f   o   r   e
0001440       r   e   s   u   m   i   n   g       n   o   r   m   a   l
0001460       m   o   n   i   t   o   r   i   n   g       o   p   e   r
0001500   a   t   i   o   n   s   .  \n                   #       S   o
0001520       w   e       n   e   e   d       t   o       a   d   j   u
0001540   s   t       t   h   i   s       v   a   r   i   a   b   l   e
0001560       s   o       G   o   d       w   i   l   l       w   a   i
0001600   t       1   0       s   e   c   o   n   d   s       o   n    
0001620   s   t   a   r   t   /   r   e   s   t   a   r   t       o   p
0001640   e   r   a   t   i   o   n   s   .  \n                   w   .
0001660   g   r   a   c   e       =       1   0   .   s   e   c   o   n
0001700   d   s  \n  \n                   #       G   o   d       w   i
0001720   l   l       s   e   n   d       S   I   G   T   E   R   M    
0001740   t   o       t   h   e       p   r   o   c   e   s   s       a
0001760   n   d       w   a   i   t       1   0       s   e   c   o   n
0002000   d   s   .  \n                   #       I   f       p   r   o
0002020   c   e   s   s       h   a   s       s   t   i   l   l       n
0002040   o   t       e   x   i   t   e   d       i   t       w   i   l
0002060   l       b   e       k   i   l   l   e   d       b   y       s
0002100   e   n   d   i   n   g       S   I   G   K   I   L   L   .  \n
0002120                   w   .   s   t   o   p   _   s   i   g   n   a
0002140   l           =       '   T   E   R   M   '  \n                
0002160   w   .   s   t   o   p   _   t   i   m   e   o   u   t       =
0002200       1   0   .   s   e   c   o   n   d   s  \n  \n            
0002220       #       G   o   d       w   i   l   l       a   l   w   a
0002240   y   s       k   e   e   p       p   r   o   c   e   s   s    
0002260   r   u   n   n   i   n   g       u   n   l   e   s   s       i
0002300   t       w   a   s       m   a   n   u   a   l   l   y       t
0002320   e   r   m   i   n   a   t   e   d   .  \n                   w
0002340   .   k   e   e   p   a   l   i   v   e  \n  \n                
0002360   #       A   l   l   o   w       c   u   s   t   o   m   i   z
0002400   a   t   i   o   n   s   .  \n                   y   i   e   l
0002420   d   (   w   )       i   f       b   l   o   c   k   _   g   i
0002440   v   e   n   ?  \n           e   n   d  \n   e   n   d  \n  \n
0002460   d   a   e   m   o   n       '   a   m   q   p   :   d   e   p
0002500   o   s   i   t   _   c   o   i   n   '   ,  \n                
0002520               s   c   r   i   p   t   :               '   a   m
0002540   q   p   _   d   a   e   m   o   n   .   r   b   '   ,  \n    
0002560                           a   r   g   u   m   e   n   t   s   :
0002600       %   w   [       d   e   p   o   s   i   t   _   c   o   i
0002620   n       ]  \n  \n   d   a   e   m   o   n       '   a   m   q
0002640   p   :   d   e   p   o   s   i   t   _   c   o   i   n   _   a
0002660   d   d   r   e   s   s   '   ,  \n                            
0002700   s   c   r   i   p   t   :               '   a   m   q   p   _
0002720   d   a   e   m   o   n   .   r   b   '   ,  \n                
0002740               a   r   g   u   m   e   n   t   s   :       %   w
0002760   [       d   e   p   o   s   i   t   _   c   o   i   n   _   a
0003000   d   d   r   e   s   s       ]  \n  \n   d   a   e   m   o   n
0003020       '   a   m   q   p   :   s   l   a   v   e   _   b   o   o
0003040   k   '   ,  \n                               s   c   r   i   p
0003060   t   :               '   a   m   q   p   _   d   a   e   m   o
0003100   n   .   r   b   '   ,  \n                               a   r
0003120   g   u   m   e   n   t   s   :       %   w   [       s   l   a
0003140   v   e   _   b   o   o   k           ]  \n  \n   d   a   e   m
0003160   o   n       '   a   m   q   p   :   m   a   r   k   e   t   _
0003200   t   i   c   k   e   r   '   ,  \n                            
0003220   s   c   r   i   p   t   :               '   a   m   q   p   _
0003240   d   a   e   m   o   n   .   r   b   '   ,  \n                
0003260               a   r   g   u   m   e   n   t   s   :       %   w
0003300   [       m   a   r   k   e   t   _   t   i   c   k   e   r    
0003320   ]  \n  \n   d   a   e   m   o   n       '   a   m   q   p   :
0003340   m   a   t   c   h   i   n   g   '   ,  \n                    
0003360           s   c   r   i   p   t   :               '   a   m   q
0003400   p   _   d   a   e   m   o   n   .   r   b   '   ,  \n        
0003420                       a   r   g   u   m   e   n   t   s   :    
0003440   %   w   [       m   a   t   c   h   i   n   g       ]  \n  \n
0003460   d   a   e   m   o   n       '   a   m   q   p   :   n   o   t
0003500   i   f   i   c   a   t   i   o   n   '   ,  \n                
0003520               s   c   r   i   p   t   :               '   a   m
0003540   q   p   _   d   a   e   m   o   n   .   r   b   '   ,  \n    
0003560                           a   r   g   u   m   e   n   t   s   :
0003600       %   w   [       e   m   a   i   l   _   n   o   t   i   f
0003620   i   c   a   t   i   o   n       ]  \n  \n   d   a   e   m   o
0003640   n       '   a   m   q   p   :   o   r   d   e   r   _   p   r
0003660   o   c   e   s   s   o   r   '   ,  \n                        
0003700       s   c   r   i   p   t   :               '   a   m   q   p
0003720   _   d   a   e   m   o   n   .   r   b   '   ,  \n            
0003740                   a   r   g   u   m   e   n   t   s   :       %
0003760   w   [       o   r   d   e   r   _   p   r   o   c   e   s   s
0004000   o   r       ]  \n  \n   d   a   e   m   o   n       '   a   m
0004020   q   p   :   p   u   s   h   e   r   _   m   a   r   k   e   t
0004040   '   ,  \n                               s   c   r   i   p   t
0004060   :               '   a   m   q   p   _   d   a   e   m   o   n
0004100   .   r   b   '   ,  \n                               a   r   g
0004120   u   m   e   n   t   s   :       %   w   [       p   u   s   h
0004140   e   r   _   m   a   r   k   e   t       ]  \n  \n   d   a   e
0004160   m   o   n       '   a   m   q   p   :   p   u   s   h   e   r
0004200   _   m   e   m   b   e   r   '   ,  \n                        
0004220       s   c   r   i   p   t   :               '   a   m   q   p
0004240   _   d   a   e   m   o   n   .   r   b   '   ,  \n            
0004260                   a   r   g   u   m   e   n   t   s   :       %
0004300   w   [       p   u   s   h   e   r   _   m   e   m   b   e   r
0004320       ]  \n  \n   d   a   e   m   o   n       '   a   m   q   p
0004340   :   t   r   a   d   e   _   e   x   e   c   u   t   o   r   '
0004360   ,  \n                               s   c   r   i   p   t   :
0004400               '   a   m   q   p   _   d   a   e   m   o   n   .
0004420   r   b   '   ,  \n                               a   r   g   u
0004440   m   e   n   t   s   :       %   w   [       t   r   a   d   e
0004460   _   e   x   e   c   u   t   o   r       ]  \n  \n   d   a   e
0004500   m   o   n       '   a   m   q   p   :   w   i   t   h   d   r
0004520   a   w   _   c   o   i   n   '   ,  \n                        
0004540       s   c   r   i   p   t   :               '   a   m   q   p
0004560   _   d   a   e   m   o   n   .   r   b   '   ,  \n            
0004600                   a   r   g   u   m   e   n   t   s   :       %
0004620   w   [       w   i   t   h   d   r   a   w   _   c   o   i   n
0004640       ]  \n  \n   D   i   r   .   g   l   o   b       "   #   {
0004660   F   i   l   e   .   d   i   r   n   a   m   e   (   _   _   F
0004700   I   L   E   _   _   )   }   /   *   *   /   *   .   r   b   "
0004720       d   o       |   f   i   l   e   |  \n           s   c   r
0004740   i   p   t       =       F   i   l   e   .   b   a   s   e   n
0004760   a   m   e   (   f   i   l   e   )  \n           n   e   x   t
0005000       i   f       %   w   [       a   m   q   p   _   d   a   e
0005020   m   o   n   .   r   b       ]   .   i   n   c   l   u   d   e
0005040   ?   (   s   c   r   i   p   t   )  \n           d   a   e   m
0005060   o   n       F   i   l   e   .   b   a   s   e   n   a   m   e
0005100   (   s   c   r   i   p   t   ,       '   .   *   '   )   ,    
0005120   s   c   r   i   p   t   :       s   c   r   i   p   t  \n   e
0005140   n   d  \n
0005143
Samir-Patel:peatio Samar$ 
Samir-Patel:peatio Samar$ god status
god: status: No such file or directory
Samir-Patel:peatio Samar$ 
Samir-Patel:peatio Samar$ god status
god: status: No such file or directory
Samir-Patel:peatio Samar$ bundle exec rake assets:precompile
rake aborted!
Psych::SyntaxError: (<unknown>): could not find expected ':' while scanning a simple key at line 8 column 3
/Users/Samar/peatio/config/application.rb:10:in `<module:Peatio>'
/Users/Samar/peatio/config/application.rb:9:in `<top (required)>'
/Users/Samar/peatio/Rakefile:5:in `require'
/Users/Samar/peatio/Rakefile:5:in `<top (required)>'
/Users/Samar/.rbenv/versions/2.5.0/bin/bundle:23:in `load'
/Users/Samar/.rbenv/versions/2.5.0/bin/bundle:23:in `<main>'
(See full trace by running task with --trace)
Samir-Patel:peatio Samar$ mysql.server start
Starting MySQL
 SUCCESS! 
Samir-Patel:peatio Samar$ 2018-02-10T07:37:18.6NZ mysqld_safe A mysqld process already exists
redis-server /usr/local/etc/redis.conf
88543:C 10 Feb 13:07:25.579 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
88543:C 10 Feb 13:07:25.580 # Redis version=4.0.8, bits=64, commit=00000000, modified=0, pid=88543, just started
88543:C 10 Feb 13:07:25.580 # Configuration loaded
88543:M 10 Feb 13:07:25.583 * Increased maximum number of open files to 10032 (it was originally set to 256).
88543:M 10 Feb 13:07:25.584 # Creating Server TCP listening socket 127.0.0.1:6379: bind: Address already in use
Samir-Patel:peatio Samar$ bundle exec rails server
Traceback (most recent call last):
	27: from bin/rails:4:in `<main>'
	26: from bin/rails:4:in `require'
	25: from /Users/Samar/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/railties-4.2.10/lib/rails/commands.rb:17:in `<top (required)>'
	24: from /Users/Samar/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/railties-4.2.10/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
	23: from /Users/Samar/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/railties-4.2.10/lib/rails/commands/commands_tasks.rb:75:in `server'
	22: from /Users/Samar/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/railties-4.2.10/lib/rails/commands/commands_tasks.rb:75:in `tap'
	21: from /Users/Samar/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/railties-4.2.10/lib/rails/commands/commands_tasks.rb:78:in `block in server'
	20: from /Users/Samar/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/railties-4.2.10/lib/rails/commands/commands_tasks.rb:78:in `require'
	19: from /Users/Samar/peatio/config/application.rb:9:in `<top (required)>'
	18: from /Users/Samar/peatio/config/application.rb:10:in `<module:Peatio>'
	17: from /Users/Samar/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/railties-4.2.10/lib/rails/application.rb:93:in `inherited'
	16: from /Users/Samar/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/activesupport-4.2.10/lib/active_support/lazy_load_hooks.rb:44:in `run_load_hooks'
	15: from /Users/Samar/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/activesupport-4.2.10/lib/active_support/lazy_load_hooks.rb:44:in `each'
	14: from /Users/Samar/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/activesupport-4.2.10/lib/active_support/lazy_load_hooks.rb:45:in `block in run_load_hooks'
	13: from /Users/Samar/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/activesupport-4.2.10/lib/active_support/lazy_load_hooks.rb:36:in `execute_hook'
	12: from /Users/Samar/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/figaro-1.1.1/lib/figaro/rails/railtie.rb:5:in `block in <class:Railtie>'
	11: from /Users/Samar/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/figaro-1.1.1/lib/figaro.rb:23:in `load'
	10: from /Users/Samar/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/figaro-1.1.1/lib/figaro/application.rb:36:in `load'
	 9: from /Users/Samar/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/figaro-1.1.1/lib/figaro/application.rb:42:in `each'
	 8: from /Users/Samar/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/figaro-1.1.1/lib/figaro/application.rb:32:in `configuration'
	 7: from /Users/Samar/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/figaro-1.1.1/lib/figaro/application.rb:64:in `global_configuration'
	 6: from /Users/Samar/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/figaro-1.1.1/lib/figaro/application.rb:56:in `raw_configuration'
	 5: from /Users/Samar/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/figaro-1.1.1/lib/figaro/application.rb:56:in `block in raw_configuration'
	 4: from /Users/Samar/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/figaro-1.1.1/lib/figaro/application.rb:60:in `parse'
	 3: from /Users/Samar/.rbenv/versions/2.5.0/lib/ruby/2.5.0/psych.rb:263:in `load'
	 2: from /Users/Samar/.rbenv/versions/2.5.0/lib/ruby/2.5.0/psych.rb:350:in `parse'
	 1: from /Users/Samar/.rbenv/versions/2.5.0/lib/ruby/2.5.0/psych.rb:402:in `parse_stream'
/Users/Samar/.rbenv/versions/2.5.0/lib/ruby/2.5.0/psych.rb:402:in `parse': (<unknown>): could not find expected ':' while scanning a simple key at line 8 column 3 (Psych::SyntaxError)
Samir-Patel:peatio Samar$

**Comment by khalidNascenia** [comment]
@samirpatelindianic can you show us your application.rb
